### ISSUE TITLE
regarding some error

### ISSUE THREAD

**Issue by bundelesneha05** [codedecde/Luna2016-Lung-Nodule-Detection#2]
**results = np.load('data.npz')** the line is from result_plot.py. In previous  preprocess code  data .npz file is not created.  Is it generated  or shoud download ??
because it throws an error.

**Comment by shreyaspadhy** [comment]
By default, the code for UNET doesn't generate the results.npyz file, but it should be a simple matter of calling the trained model, running the test data through it, and saving the outputs.

You could also check out a Pytorch implementation for this UNet model if that's more up your alley - [UNet-Zoo](https://github.com/shreyaspadhy/UNet-Zoo)
