### ISSUE TITLE
Regarding the predicted output...

### ISSUE THREAD

**Issue by bundelesneha05** [codedecde/Luna2016-Lung-Nodule-Detection#6]
I trained the given U-net model on 1459 samples of LUNA16 database with dice coefficient 0.92 with tensorflow(1.3.0) as well as theano(1.0.1)   backend. But it gives me output as below,

![predicted_image1](https://user-images.githubusercontent.com/30527585/37751684-d7f0005c-2db9-11e8-918c-a31647b20b70.png)

![predicted_image](https://user-images.githubusercontent.com/30527585/37751595-4a2ebc2c-2db9-11e8-9e41-6195feeb469b.png)

It is not same as the results given in this documentation. How should I solve this problem???
Thanks in advance!

**Comment by sushmakulkani** [comment]
I am also facing same problem. I am using same database and annotation as in the documentation. Not getting how to proceed  for getting results as updated by @shreyaspadhy  in the documentation ?
Please reply 
Thanks in advance!!

**Comment by mrudangpandya** [comment]
i am getting " No such file or directory: 'data.npz'". what data.npz file contents ?

**Comment by bundelesneha05** [comment]
@mrudangpandya ,
have you  trained the model by using tensorflow or theano? about your question in **result.py**  file I think, data.npz might contain the numpy files of test and predicted images.

**Comment by bundelesneha05** [comment]
My humble request to the @shreyaspadhy  and @codedecde,  please let us answered about our doubt.

**Comment by codedecde** [comment]
Try visualising the train data once ? Because if you are getting a dice coefficient of 0.92, that means the model is training, and the predicted mask and the gold mask have a significant overlap. 
I can take a better look at it after the 7th of May.

**Comment by shreyaspadhy** [comment]
Hi, unfortunately right now our LUNA_Unet.py doesn't save the results as data.npz by default. I believe I had saved some results by manually modifying the LUNA_Unet.py code to save results into a data.npz file. Here is what I suggest - 

In LUNA_UNet.py, after calling model.fit, call model.predict() and save the results as a Python dictionary `data`, where it has the following keys `imgs_test_X` (The original images as numpy arrays), `imgs_test_Y`(the gold label masks), `imgs_test_Pred` (the output from UNet).

Then you could just use Results_Plot.py (the code for plotting such a dictionary is commented out later, you can just uncomment it).

**Comment by mrudangpandya** [comment]
ok thank you

I will do this changes..

Thank you
